name: End-to-end tests

on:
  push:
    branches:
    - 'master'
  schedule:
    - cron : '0 5 * * *'

jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    name: E2E on Firefox
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: firefox
          headless: true
          config-file: cypress.json
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Clean contribution production
        run: python clean-contrib-publi.py
        env:
          HEADERS_AUTH_BASIC: ${{ secrets.HEADERS_AUTH_BASIC }}
          SCANR_API_URL_CONTRIBUTE: ${{ secrets.SCANR_API_URL_CONTRIBUTE }}
      - name: Notify in slack
      run: |
        curl -X POST -H 'Content-type: application/json' --data '{"text":"Everything is under control on ScanR production"}' ${{ secrets.SLACK_WEBHOOK }}